




.build/micro/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/micro/src
	@echo [93msrc/sketch.ino[0m
	@/home/jochemste/.local/bin/ino preproc  -o $@ $^


all : .build/micro/src/sketch.cpp
	@true

